# Site/SEO settings
email: aaizman@umich.edu
baseurl: ""
permalink: /:year/:month/:day/:title/
google_analytics: 

name: Ania Aizman
title: Ania Aizman's teaching portfolio > past courses > Art and Anarchism > student projects
description: >

url: https://aizman.github.io
default_img: /assets/images/seo.jpg
#social:
#  - name: twitter
#    url: https://twitter.com/thomasvaeth
#  - name: instagram
#    url: https://www.instagram.com/thomas.vaeth/
#  - name: linkedin
#    url: https://www.linkedin.com/in/thomasvaeth/
#  - name: github
#    url: https://github.com/samesies
#  - name: codepen
#    url: https://codepen.io/thomasvaeth/

# Contact settings
contact_img: /assets/images/placeholder-28.jpg
formcarry: https://formcarry.com/s/HkIo0nMb7

# Disqus settings
disqus: test-apkdzgmqhj

# MailChimp settings
mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f

# Author settings
author:
  - name: Ania Aizman
    bio: "Ania Aizman holds a Ph.D. from Harvard and a bachelor’s degree from the University of Chicago, both in Comparative Literature, and with a focus on Russian and Czech. At the University of Michigan, she is writing a book: 'From Tolstoy to Pussy Riot: Anarchist Currents in Russian Culture. Based on archival research and oral histories with artists, writers, and activists, it finds missing links between the nineteenth-century anarchist movements, Soviet underground cultures, and contemporary collectives. It also proposes an anarchist literary theory. Ania’s other research project focuses on contemporary theater in Russia. For this project, she conducted interviews and performance and rehearsal observations between 2014-2018. Her translations of plays by contemporary playwrights Mikhail Durnenkov, Mikhail Ugarov, and Elena Gremina were published by the Performing Arts Journal and Columbia University Press. An article exploring the anarchist aesthetics of Pussy Riot and the OBERIU was published in The Russian Review in January 2019. Ania has also written about trophy films, Russian “New Drama,” and the politics of Soviet children’s poems. Ania is teaching introductory and advanced courses on the cultures of Russia and Eastern Europe at the University of Michigan. In her courses, she shares her love of archival and library research with students and integrates creative assignments inspired by her research topics."
    url: aizman.github.io

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts: 
      - 'tag.html'
    title: 'The Barber Theme'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
#  - tags_list
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
